@startuml

terminal -> cli: execute
activate cli
cli -> JSONPlaceholderClient: fetch
JSONPlaceholderClient --> cli: Decoded<[Person]>
cli -> cli: map(Decoded<[Person]>) -> pretty printed JSON String
cli -> terminal: print
deactivate cli

@enduml